QUESTION:Research and write 20 inbuilt method on pandas and numpy with examples for each

In [1]:
import numpy as np
import pandas as pd

1.ARRAY FUNCTION:an array is used to create a one-dimensional or multidimensional arrays from scratch.

In [2]:
#example of array.
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

2.SUM FUNCTION:sums(ADDS) up array elements over a given axis

In [3]:
#example
SUM = np.sum(my_list)
print(SUM)

15


3.AVERAGE Function:Computes the weighted average along the specified axis

In [4]:
#example
np.average(my_list)
print(np.average(my_list))

3.0


4.MAX FUNCTION:Returns the maximum (highest value) of an array or maximum along an axis

In [5]:
#example
values = [2,4,-1,56,90,105,1005]
print(np.max(values))

1005


5.MIN FUNCTION:Returns the minimum(lowest value) of an array or minimum along an axis.

In [6]:
#examle
np.min(values)
print(np.min(values))

-1


6.APPEND FUNCTION:Append(add) values to the end of an array.

In [7]:
#example
#adding up numbers in "my_list" and "values" using append function
x = np.array(my_list)
w = np.append(x,(values))
print(w)

[   1    2    3    4    5    2    4   -1   56   90  105 1005]


7.SUBTRACT FUNCTION:Subtracts arguments, element-wise

In [8]:
#example
#subtracting 25 from the sum of values in "my_list"
y = np.sum(my_list)
z = 25
print(np.subtract(y,z))

-10


8.ARANGE FUNCTION:Returns evenly spaced values within a given interval with some step size important parameters;STEP-this is the space between values

In [9]:
#example 1.
doc = np.arange(7)
print(doc)
#example 2
np.arange(5,10,2)

[0 1 2 3 4 5 6]


array([5, 7, 9])

9.SHAPE:Return the shape of an array

In [10]:
#example
np.shape(np.eye(5))

(5, 5)

10.ONES FUNCTION:Returns a new array of given shape and type, filled with ones

In [11]:
#Example
line = np.ones((5,3),dtype = int)
print(line)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


11.ARRAY of ZERO:Returns a new array of given shape and type, filled with zeros important parameters are; Shape-shape of the resultant array,DTYPE-desired data type of resultant array which could be "int" 0r default "float"

In [12]:
np.zeros((7,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

12.LINSPACE:Creates an array with evenly spaced float numbers over a specified interval

In [13]:
#important parameters;START-starting index,End-last index,NUM-number of samplesto generate,default=50
#example
np.linspace(10,100,10)


array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

13.UNIFORM SAMPLES:Generates a random sample from a uniform distribution between lower and higher limit value

In [14]:
#example for linsace
np.random.uniform(size = 5)

array([0.81100855, 0.66095078, 0.02357224, 0.09695013, 0.4595136 ])

14. RANDOM.RANDINT(Random.randint): this generates n random interger samples within a range

In [15]:
#Random.randint example
np.random.randint(5,10,10)

array([9, 5, 7, 8, 9, 9, 6, 7, 8, 7])

15.MEAN FUNCTION: This is used to get the mean of the array

In [16]:
#example using the mean operator function
arr = np.array([10,10,10,6,4,6])
np.mean(arr,dtype="int")

7

16.MEDIAN OPERATOR FUNCTION: This returns the median value of an array i.e the middle value

In [17]:
#example
np.median(arr)

8.0

17.RESHAPE:This is returns an array containing the same data with a new shape

In [18]:
A = np.random.randint(15,size=(4,3))
A

array([[11, 13, 13],
       [10,  8,  3],
       [ 0,  3,  1],
       [ 2,  4, 14]])

In [19]:
A.reshape(3,4)

array([[11, 13, 13, 10],
       [ 8,  3,  0,  3],
       [ 1,  2,  4, 14]])

18.SORT FUNCTIN: This sorts the array and returns it. important parameters:Kind-sorting algorithm to use{'quicksort','mergersort','heapsoort','stable'}

In [20]:
mylist = np.array ([3,4,6,7,9,1,4,5,34,23,15,67,9,0,1,2])
np.sort(mylist)


array([ 0,  1,  1,  2,  3,  4,  4,  5,  6,  7,  9,  9, 15, 23, 34, 67])

19.WHERE:This returns elements from an array where a condition satisfies

In [21]:
#important parameters;CONDITION-condition to match.if true yield x otherwise y
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.where(b>3)#get the index

(array([1, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [23]:
b[np.where(b>3)] #get values

array([ 4,  5,  6,  7,  8,  9, 10, 11])

20.DIFFERENCE FUNCTION:This returns all the unique elements from an array 1 that are not present in arr 2

In [24]:
arr1 = np.array([2,1,4,5,7,9])
arr2 = np.array([8,9,10,11,6])
np.setdiff1d(arr1,arr2)

array([1, 2, 4, 5, 7])

INBUILT FUNCTIONS IN PANDAS

1.SERIES

In [25]:
#EXAMPLE1
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d, index=['a', 'b', 'c'])
ser

a    1
b    2
c    3
dtype: int64

In [30]:
#CREATING A DATAFRAME
data = {"Name":["Jane","Angela","John"], "Age":[20,25,18], "Address":["Bauchi","Jos","Gombe"]}
df = pd.DataFrame(data)
df

Name  Age Address
0    Jane   20  Bauchi
1  Angela   25     Jos
2    John   18   Gombe

2. SUM

In [31]:
#EXAMPLE,suming to get the total age in the data frame
df["Age"].sum()


63

3.MEAN

In [32]:
#EXAMPLEcalcu;ating the mean of the ages
df["Age"].mean()

21.0

4.MIN

In [33]:
#EXAMPLE_finding the minimum value from ages
df["Age"].min()

18

5.MAX

In [34]:
#EXAMPLE_Finding the maximum age value
df["Age"].max()

25

6.LOC:Access a group of rows and columns by label(s) or a boolean array.

In [37]:
#EXAMPLE
df.loc[0:1]

Name  Age Address
0    Jane   20  Bauchi
1  Angela   25     Jos

In [38]:
df.loc[0:2]

Name  Age Address
0    Jane   20  Bauchi
1  Angela   25     Jos
2    John   18   Gombe

7.iloc:
Purely integer-location based indexing for selection by position.
iloc is primarily integer position based (from ``0`` to
``length-1`` of the axis), but may also be used with a boolean
array.

In [39]:
df.iloc[0:2]

Name  Age Address
0    Jane   20  Bauchi
1  Angela   25     Jos

8.SLICE

In [40]:
#EXAMPLES ON SLICE
names = ["Joy","Mary","Martha","Balkisu","Ify"]
names[0::2]

['Joy', 'Martha', 'Ify']

In [42]:
df["Name"][0:3]

0      Jane
1    Angela
2      John
Name: Name, dtype: object

9.ADD:this can be used to add a new row or column to a data frame

In [46]:
#examle_adding a new column to a data frame
